apiVersion: v1
data:
  DD_ADMIN_PASSWORD: dmtlMHluNVFhS0FGeHhIY29Lazd0aw==
  DD_CREDENTIAL_AES_256_KEY: R3lxeGpzRVN5OXRwd1VxaXdvVkJ5U3ZiN1Z6SzJZbTVHMzd3MWZwWlQ1Q3IwQ3Axazc5YzFsR3YwVHNqNzBYN0lmRGVPSWhZNjVHNmpGTk45dUp4UXd6Z1NmVWdnVzFpNm9EZXk3Q2YyQWFBancwNXZYd2ZHb3Axb
VFCN3RjZ3k=
  DD_SECRET_KEY: M2JQM0FRa0pQWTB5bHNndGpUQkxOMXVnMVhKeGtWeHhlWUpKYW9lelc3SlN1R3pBcW9YcTVIMUhFVjBhTHFwZG1KVWxZeWhFMUhkQ0tiWG9hWnl0cHBXSXFjb2NSTDBXQ3hQQ0FUWjNRbVU0NmxJWG52UXhpTWRxU0pMcnpEcVE=
  METRICS_HTTP_AUTH_PASSWORD: TzlsRjVNT1dKR0tmY3l0VjRvaGZxUnZIWUh0emlCSHI=
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/resource-policy: keep
  creationTimestamp: "2024-04-23T07:26:43Z"
  labels:
    app.kubernetes.io/instance: defectdojo-1713857194
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: defectdojo
    helm.sh/chart: defectdojo-1.6.123
  name: defectdojo
  resourceVersion: "5549738"
  uid: ac222e7f-ac42-4ff5-8c6e-9306933a2eb9
type: Opaque

---

apiVersion: v1
data:
  postgresql-password: QWxzaGF5YUAyMDI0
  postgresql-postgres-password: QWxzaGF5YUAyMDI0
  postgresql-username: QWxzaGF5YQ==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"postgresql-password":"QWxzaGF5YUAyMDI0","postgresql-username":"QWxzaGF5YQ=="},"kind":"Secret","metadata":{"annotations":{},"name":"defectdojo-postgresql-spe
cific","namespace":"dojo"},"type":"Opaque"}
  creationTimestamp: "2024-04-23T07:37:35Z"
  name: defectdojo-postgresql-specific
  resourceVersion: "5554422"
  uid: afd15751-cd60-40a6-bec3-d5bda6da9544
type: Opaque
---

apiVersion: v1
data:
  rabbitmq-erlang-cookie: M3hhZlg5UDBGVkE3eWxVVVdqV0JWeTNYTXdDMnhuVXk=
  rabbitmq-password: aG91ZUJ4N3VVdg==
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/resource-policy: keep
  creationTimestamp: "2024-04-23T07:28:10Z"
  labels:
    app.kubernetes.io/instance: defectdojo-1713857281
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: defectdojo
    helm.sh/chart: defectdojo-1.6.123
  name: defectdojo-rabbitmq-specific
  resourceVersion: "5550512"
  uid: 682035e9-8ceb-4477-a136-01ac96d99cc0
type: Opaque
