apiVersion: v1
kind: Secret
metadata:
  name: defectdojo
  labels:
    app.kubernetes.io/instance: defectdojo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: defectdojo
    helm.sh/chart: defectdojo-1.6.183
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/resource-policy: keep
type: Opaque
data:
  DD_ADMIN_PASSWORD: SmJCOUlNV0MwMlNyQURNeVl6bWxlOQ==
  DD_CREDENTIAL_AES_256_KEY: NUpQaFJBWTExc0NYb0I5dDJZbEZNZDF4NUdBTDJ6T3o5MkFmSVpORll5cWFwNWd1eHBrMUs0aVU0eHY0cjF6UFpZcWdCS1dQZURmMVFlczBHNlZhSUNGY2ZRNTU4Mm4yQzBHb1QxYnJPYld3OElYMjU3RjdIVFRDeDF0VkNhcXc=
  DD_SECRET_KEY: ZmJMams1WXl6WHRrd1ZYVFROc0pOMUNRa3M4M0I2a1pBTDdvWXdsZ3FDTXczdmczd2xlMXByUjhTNWFOd2RtTXZyVzI0VW9JMnBzeDRJV01TNXR1WTdTTE1XNDlYTkdxOURYRU0zZWVGYUNMTm1ZZFN5TEE2bGhybnpub2lUd0Q=
  METRICS_HTTP_AUTH_PASSWORD: b2oyeHYybTh2S3RmYkRkRTdhYTdzclNxbUh5d2hSSkQ=

---

apiVersion: v1
kind: Secret
metadata:
  name: defectdojo-postgresql-specific
  labels:
    app.kubernetes.io/instance: defectdojo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: defectdojo
    helm.sh/chart: defectdojo-1.6.183
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/resource-policy: keep
type: Opaque
data:
  postgresql-password: NXdlVm92VEc0R0FWb05aSw==
  postgresql-postgres-password: NXdlVm92VEc0R0FWb05aSw==

---

apiVersion: v1
kind: Secret
metadata:
  name: defectdojo-redis-specific
  labels:
    app.kubernetes.io/instance: defectdojo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: defectdojo
    helm.sh/chart: defectdojo-1.6.183
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/resource-policy: keep
type: Opaque
data:
  redis-password: dUo5R0hGNHE0dg==

---

apiVersion: v1
kind: Secret
metadata:
  name: defectdojo-rabbitmq-specific
  labels:
    app.kubernetes.io/instance: defectdojo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: defectdojo
    helm.sh/chart: defectdojo-1.6.183
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/resource-policy: keep
type: Opaque
data:
  rabbitmq-password: dUo5R0hGNHE0dg==
  rabbitmq-erlang-cookie: $(dd if=/dev/urandom bs=30 count=1 | base64)
